package widget

import (
	"fyne.io/fyne/widget"

	qlang "github.com/topxeq/qlang/spec"
)

// Exports is the export table of this module.
//
var Exports = map[string]interface{}{
	"_name": "fyne.io/fyne/widget",

	"ButtonAlignCenter":      widget.ButtonAlignCenter,
	"ButtonAlignLeading":     widget.ButtonAlignLeading,
	"ButtonAlignTrailing":    widget.ButtonAlignTrailing,
	"ButtonIconLeadingText":  widget.ButtonIconLeadingText,
	"ButtonIconTrailingText": widget.ButtonIconTrailingText,
	"DefaultButton":          widget.DefaultButton,
	"Horizontal":             widget.Horizontal,
	"PrimaryButton":          widget.PrimaryButton,
	"ScrollBoth":             widget.ScrollBoth,
	"ScrollHorizontalOnly":   widget.ScrollHorizontalOnly,
	"ScrollVerticalOnly":     widget.ScrollVerticalOnly,
	"TabLocationBottom":      widget.TabLocationBottom,
	"TabLocationLeading":     widget.TabLocationLeading,
	"TabLocationTop":         widget.TabLocationTop,
	"TabLocationTrailing":    widget.TabLocationTrailing,
	"Vertical":               widget.Vertical,

	"TextGridStyleDefault":    widget.TextGridStyleDefault,
	"TextGridStyleWhitespace": widget.TextGridStyleWhitespace,

	"DestroyRenderer":         widget.DestroyRenderer,
	"Refresh":                 widget.Refresh,
	"Renderer":                widget.Renderer,
	"ShowModalPopUp":          widget.ShowModalPopUp,
	"ShowPopUp":               widget.ShowPopUp,
	"ShowPopUpAtPosition":     widget.ShowPopUpAtPosition,
	"ShowPopUpMenuAtPosition": widget.ShowPopUpMenuAtPosition,

	"NewToolbarAction":    widget.NewToolbarAction,
	"NewToolbarSeparator": widget.NewToolbarSeparator,
	"NewToolbarSpacer":    widget.NewToolbarSpacer,

	"AccordionContainer":     qlang.StructOf((*widget.AccordionContainer)(nil)),
	"accordioncontainer":     widget.NewAccordionContainer,
	"NewAccordionContainer":  widget.NewAccordionContainer,
	"AccordionItem":          qlang.StructOf((*widget.AccordionItem)(nil)),
	"accordionitem":          widget.NewAccordionItem,
	"NewAccordionItem":       widget.NewAccordionItem,
	"NewHBox":                widget.NewHBox,
	"NewVBox":                widget.NewVBox,
	"NewButton":              widget.NewButton,
	"NewButtonWithIcon":      widget.NewButtonWithIcon,
	"check":                  widget.NewCheck,
	"NewCheck":               widget.NewCheck,
	"CustomTextGridStyle":    qlang.StructOf((*widget.CustomTextGridStyle)(nil)),
	"entry":                  widget.NewEntry,
	"NewEntry":               widget.NewEntry,
	"NewMultiLineEntry":      widget.NewMultiLineEntry,
	"NewPasswordEntry":       widget.NewPasswordEntry,
	"form":                   widget.NewForm,
	"NewForm":                widget.NewForm,
	"FormItem":               qlang.StructOf((*widget.FormItem)(nil)),
	"formitem":               widget.NewFormItem,
	"NewFormItem":            widget.NewFormItem,
	"NewGroup":               widget.NewGroup,
	"NewGroupWithScroller":   widget.NewGroupWithScroller,
	"NewHyperlink":           widget.NewHyperlink,
	"NewHyperlinkWithStyle":  widget.NewHyperlinkWithStyle,
	"Icon":                   qlang.StructOf((*widget.Icon)(nil)),
	"icon":                   widget.NewIcon,
	"NewIcon":                widget.NewIcon,
	"NewLabel":               widget.NewLabel,
	"NewLabelWithStyle":      widget.NewLabelWithStyle,
	"menu":                   widget.NewMenu,
	"NewMenu":                widget.NewMenu,
	"NewPopUp":               widget.NewPopUp,
	"NewPopUpAtPosition":     widget.NewPopUpAtPosition,
	"NewPopUpMenu":           widget.NewPopUpMenu,
	"NewPopUpMenuAtPosition": widget.NewPopUpMenuAtPosition,
	"NewModalPopUp":          widget.NewModalPopUp,
	"ProgressBar":            qlang.StructOf((*widget.ProgressBar)(nil)),
	"progressbar":            widget.NewProgressBar,
	"NewProgressBar":         widget.NewProgressBar,
	"ProgressBarInfinite":    qlang.StructOf((*widget.ProgressBarInfinite)(nil)),
	"progressbarinfinite":    widget.NewProgressBarInfinite,
	"NewProgressBarInfinite": widget.NewProgressBarInfinite,
	"radio":                  widget.NewRadio,
	"NewRadio":               widget.NewRadio,
	"scrollcontainer":        widget.NewScrollContainer,
	"NewScrollContainer":     widget.NewScrollContainer,
	"NewHScrollContainer":    widget.NewHScrollContainer,
	"NewVScrollContainer":    widget.NewVScrollContainer,
	"select":                 widget.NewSelect,
	"NewSelect":              widget.NewSelect,
	"selectentry":            widget.NewSelectEntry,
	"NewSelectEntry":         widget.NewSelectEntry,
	"Slider":                 qlang.StructOf((*widget.Slider)(nil)),
	"slider":                 widget.NewSlider,
	"NewSlider":              widget.NewSlider,
	"SplitContainer":         qlang.StructOf((*widget.SplitContainer)(nil)),
	"NewHSplitContainer":     widget.NewHSplitContainer,
	"NewVSplitContainer":     widget.NewVSplitContainer,
	"tabcontainer":           widget.NewTabContainer,
	"NewTabContainer":        widget.NewTabContainer,
	"TabItem":                qlang.StructOf((*widget.TabItem)(nil)),
	"NewTabItem":             widget.NewTabItem,
	"NewTabItemWithIcon":     widget.NewTabItemWithIcon,
	"TextGrid":               qlang.StructOf((*widget.TextGrid)(nil)),
	"NewTextGrid":            widget.NewTextGrid,
	"NewTextGridFromString":  widget.NewTextGridFromString,
	"TextGridCell":           qlang.StructOf((*widget.TextGridCell)(nil)),
	"TextGridRow":            qlang.StructOf((*widget.TextGridRow)(nil)),
	"Toolbar":                qlang.StructOf((*widget.Toolbar)(nil)),
	"toolbar":                widget.NewToolbar,
	"NewToolbar":             widget.NewToolbar,
	"ToolbarAction":          qlang.StructOf((*widget.ToolbarAction)(nil)),
	"ToolbarSeparator":       qlang.StructOf((*widget.ToolbarSeparator)(nil)),
	"ToolbarSpacer":          qlang.StructOf((*widget.ToolbarSpacer)(nil)),
}
