package plotter

import (
	"gonum.org/v1/plot/plotter"

	qlang "github.com/topxeq/qlang/spec"
)

// Exports is the export table of this module.
//
var Exports = map[string]interface{}{
	"_name": "gonum.org/v1/plot/plotter",

	"MidStep":  plotter.MidStep,
	"NoStep":   plotter.NoStep,
	"PostStep": plotter.PostStep,
	"PreStep":  plotter.PreStep,

	"DefaultCapWidth":          plotter.DefaultCapWidth,
	"DefaultFont":              plotter.DefaultFont,
	"DefaultFontSize":          plotter.DefaultFontSize,
	"DefaultGlyphStyle":        plotter.DefaultGlyphStyle,
	"DefaultGridLineStyle":     plotter.DefaultGridLineStyle,
	"DefaultLineStyle":         plotter.DefaultLineStyle,
	"DefaultQuartMedianStyle":  plotter.DefaultQuartMedianStyle,
	"DefaultQuartWhiskerStyle": plotter.DefaultQuartWhiskerStyle,
	"ErrInfinity":              plotter.ErrInfinity,
	"ErrNaN":                   plotter.ErrNaN,
	"ErrNoData":                plotter.ErrNoData,

	"CheckFloats":         plotter.CheckFloats,
	"NewLinePoints":       plotter.NewLinePoints,
	"PaletteThumbnailers": plotter.PaletteThumbnailers,
	"Range":               plotter.Range,
	"XYRange":             plotter.XYRange,

	"barchart":      plotter.NewBarChart,
	"NewBarChart":   plotter.NewBarChart,
	"BoxPlot":       qlang.StructOf((*plotter.BoxPlot)(nil)),
	"boxplot":       plotter.NewBoxPlot,
	"NewBoxPlot":    plotter.NewBoxPlot,
	"ColorBar":      qlang.StructOf((*plotter.ColorBar)(nil)),
	"Contour":       qlang.StructOf((*plotter.Contour)(nil)),
	"contour":       plotter.NewContour,
	"NewContour":    plotter.NewContour,
	"field":         plotter.NewField,
	"NewField":      plotter.NewField,
	"Flow":          qlang.StructOf((*plotter.Flow)(nil)),
	"Function":      qlang.StructOf((*plotter.Function)(nil)),
	"function":      plotter.NewFunction,
	"NewFunction":   plotter.NewFunction,
	"GlyphBoxes":    qlang.StructOf((*plotter.GlyphBoxes)(nil)),
	"glyphboxes":    plotter.NewGlyphBoxes,
	"NewGlyphBoxes": plotter.NewGlyphBoxes,
	"Grid":          qlang.StructOf((*plotter.Grid)(nil)),
	"grid":          plotter.NewGrid,
	"NewGrid":       plotter.NewGrid,
	"HeatMap":       qlang.StructOf((*plotter.HeatMap)(nil)),
	"heatmap":       plotter.NewHeatMap,
	"NewHeatMap":    plotter.NewHeatMap,
	"Histogram":     qlang.StructOf((*plotter.Histogram)(nil)),
	"histogram":     plotter.NewHistogram,
	"NewHistogram":  plotter.NewHistogram,
	"NewHist":       plotter.NewHist,
	"HistogramBin":  qlang.StructOf((*plotter.HistogramBin)(nil)),
	"image":         plotter.NewImage,
	"NewImage":      plotter.NewImage,
	"Labels":        qlang.StructOf((*plotter.Labels)(nil)),
	"labels":        plotter.NewLabels,
	"NewLabels":     plotter.NewLabels,
	"Line":          qlang.StructOf((*plotter.Line)(nil)),
	"line":          plotter.NewLine,
	"NewLine":       plotter.NewLine,
	"Polygon":       qlang.StructOf((*plotter.Polygon)(nil)),
	"polygon":       plotter.NewPolygon,
	"NewPolygon":    plotter.NewPolygon,
	"QuartPlot":     qlang.StructOf((*plotter.QuartPlot)(nil)),
	"quartplot":     plotter.NewQuartPlot,
	"NewQuartPlot":  plotter.NewQuartPlot,
	"sankey":        plotter.NewSankey,
	"NewSankey":     plotter.NewSankey,
	"Scatter":       qlang.StructOf((*plotter.Scatter)(nil)),
	"scatter":       plotter.NewScatter,
	"NewScatter":    plotter.NewScatter,
	"XErrorBars":    qlang.StructOf((*plotter.XErrorBars)(nil)),
	"xerrorbars":    plotter.NewXErrorBars,
	"NewXErrorBars": plotter.NewXErrorBars,
	"XValues":       qlang.StructOf((*plotter.XValues)(nil)),
	"XY":            qlang.StructOf((*plotter.XY)(nil)),
	"XYs":           qlang.StructOf((*plotter.XYs)(nil)),
	"XYLabels":      qlang.StructOf((*plotter.XYLabels)(nil)),
	"XYValues":      qlang.StructOf((*plotter.XYValues)(nil)),
	"XYZ":           qlang.StructOf((*plotter.XYZ)(nil)),
	"YErrorBars":    qlang.StructOf((*plotter.YErrorBars)(nil)),
	"yerrorbars":    plotter.NewYErrorBars,
	"NewYErrorBars": plotter.NewYErrorBars,
	"YValues":       qlang.StructOf((*plotter.YValues)(nil)),
}
