package keyboard

import (
	"github.com/eiannone/keyboard"

	qlang "github.com/topxeq/qlang/spec"
)

// Exports is the export table of this module.
//
var Exports = map[string]interface{}{
	"_name": "github.com/eiannone/keyboard",

	"KeyArrowDown":      keyboard.KeyArrowDown,
	"KeyArrowLeft":      keyboard.KeyArrowLeft,
	"KeyArrowRight":     keyboard.KeyArrowRight,
	"KeyArrowUp":        keyboard.KeyArrowUp,
	"KeyBackspace":      keyboard.KeyBackspace,
	"KeyBackspace2":     keyboard.KeyBackspace2,
	"KeyCtrl2":          keyboard.KeyCtrl2,
	"KeyCtrl3":          keyboard.KeyCtrl3,
	"KeyCtrl4":          keyboard.KeyCtrl4,
	"KeyCtrl5":          keyboard.KeyCtrl5,
	"KeyCtrl6":          keyboard.KeyCtrl6,
	"KeyCtrl7":          keyboard.KeyCtrl7,
	"KeyCtrl8":          keyboard.KeyCtrl8,
	"KeyCtrlA":          keyboard.KeyCtrlA,
	"KeyCtrlB":          keyboard.KeyCtrlB,
	"KeyCtrlBackslash":  keyboard.KeyCtrlBackslash,
	"KeyCtrlC":          keyboard.KeyCtrlC,
	"KeyCtrlD":          keyboard.KeyCtrlD,
	"KeyCtrlE":          keyboard.KeyCtrlE,
	"KeyCtrlF":          keyboard.KeyCtrlF,
	"KeyCtrlG":          keyboard.KeyCtrlG,
	"KeyCtrlH":          keyboard.KeyCtrlH,
	"KeyCtrlI":          keyboard.KeyCtrlI,
	"KeyCtrlJ":          keyboard.KeyCtrlJ,
	"KeyCtrlK":          keyboard.KeyCtrlK,
	"KeyCtrlL":          keyboard.KeyCtrlL,
	"KeyCtrlLsqBracket": keyboard.KeyCtrlLsqBracket,
	"KeyCtrlM":          keyboard.KeyCtrlM,
	"KeyCtrlN":          keyboard.KeyCtrlN,
	"KeyCtrlO":          keyboard.KeyCtrlO,
	"KeyCtrlP":          keyboard.KeyCtrlP,
	"KeyCtrlQ":          keyboard.KeyCtrlQ,
	"KeyCtrlR":          keyboard.KeyCtrlR,
	"KeyCtrlRsqBracket": keyboard.KeyCtrlRsqBracket,
	"KeyCtrlS":          keyboard.KeyCtrlS,
	"KeyCtrlSlash":      keyboard.KeyCtrlSlash,
	"KeyCtrlSpace":      keyboard.KeyCtrlSpace,
	"KeyCtrlT":          keyboard.KeyCtrlT,
	"KeyCtrlTilde":      keyboard.KeyCtrlTilde,
	"KeyCtrlU":          keyboard.KeyCtrlU,
	"KeyCtrlUnderscore": keyboard.KeyCtrlUnderscore,
	"KeyCtrlV":          keyboard.KeyCtrlV,
	"KeyCtrlW":          keyboard.KeyCtrlW,
	"KeyCtrlX":          keyboard.KeyCtrlX,
	"KeyCtrlY":          keyboard.KeyCtrlY,
	"KeyCtrlZ":          keyboard.KeyCtrlZ,
	"KeyDelete":         keyboard.KeyDelete,
	"KeyEnd":            keyboard.KeyEnd,
	"KeyEnter":          keyboard.KeyEnter,
	"KeyEsc":            keyboard.KeyEsc,
	"KeyF1":             keyboard.KeyF1,
	"KeyF10":            keyboard.KeyF10,
	"KeyF11":            keyboard.KeyF11,
	"KeyF12":            keyboard.KeyF12,
	"KeyF2":             keyboard.KeyF2,
	"KeyF3":             keyboard.KeyF3,
	"KeyF4":             keyboard.KeyF4,
	"KeyF5":             keyboard.KeyF5,
	"KeyF6":             keyboard.KeyF6,
	"KeyF7":             keyboard.KeyF7,
	"KeyF8":             keyboard.KeyF8,
	"KeyF9":             keyboard.KeyF9,
	"KeyHome":           keyboard.KeyHome,
	"KeyInsert":         keyboard.KeyInsert,
	"KeyPgdn":           keyboard.KeyPgdn,
	"KeyPgup":           keyboard.KeyPgup,
	"KeySpace":          keyboard.KeySpace,
	"KeyTab":            keyboard.KeyTab,

	"Close":     keyboard.Close,
	"GetKeys":   keyboard.GetKeys,
	"IsStarted": keyboard.IsStarted,
	"Open":      keyboard.Open,

	"GetKey":       keyboard.GetKey,
	"GetSingleKey": keyboard.GetSingleKey,

	"KeyEvent": qlang.StructOf((*keyboard.KeyEvent)(nil)),
}
