package vcl

import (
	"github.com/topxeq/govcl/vcl"
	"github.com/topxeq/govcl/vcl/api"
	"github.com/topxeq/govcl/vcl/rtl"
	"github.com/topxeq/tk"
	"runtime"
)

func initLCLLib() (result error) {

	defer func() {
		if r := recover(); r != nil {
			// fmt.Printf("initLCLLib: %v\n", r)

			result = tk.Errf("initLCLLib: %v\n", r)
		}
	}()

	api.DoLibInit()

	result = nil

	return result
}

// func syncInitLCL() error {
// 	var errT error

// 	vcl.ThreadSync(func() {
// 		initLCL()
// 	})

// 	return errT
// }

func initLCL() error {

	runtime.LockOSThread()

	// startThreadID := tk.GetCurrentThreadID()

	api.CloseLib()

	errT := initLCLLib()

	if errT != nil {
		tk.Pl("failed to init lib: %v, try to download the LCL lib...", errT)

		applicationPathT := tk.GetApplicationPath()

		osT := tk.GetOSName()

		if tk.Contains(osT, "inux") {
			rs := tk.DownloadFile("http://scripts.frenchfriend.net/pub/liblcl.so", applicationPathT, "liblcl.so", false)

			if tk.IsErrorString(rs) {
				tk.Pl("failed to download LCL file.")
				return tk.Errf("failed to download LCL file.")
			}
		} else if tk.Contains(osT, "arwin") {
			rs := tk.DownloadFile("http://scripts.frenchfriend.net/pub/liblcl.dylib", applicationPathT, "liblcl.dylib", false)

			if tk.IsErrorString(rs) {
				tk.Pl("failed to download LCL file.")
				return tk.Errf("failed to download LCL file.")
			}
		} else {
			rs := tk.DownloadFile("http://scripts.frenchfriend.net/pub/liblcl.dll", applicationPathT, "liblcl.dll", false)

			if tk.IsErrorString(rs) {
				tk.Pl("failed to download LCL file.")
				return tk.Errf("failed to download LCL file.")
			}
		}

		errT = initLCLLib()

		if errT != nil {
			tk.Pl("failed to install lib: %v", errT)
			return tk.Errf("failed to install lib: %v", errT)
		}
	}

	api.DoResInit()

	api.DoImportInit()

	api.DoDefInit()

	rtl.DoRtlInit()

	vcl.DoInit()

	// if verboseG {

	// 	endThreadID := tk.GetCurrentThreadID()

	// 	tk.Pl("start tid: %v, end tid: %v", startThreadID, endThreadID)

	// 	if endThreadID != startThreadID {
	// 		return tk.Errf("failed to init lcl lib: %v", "thread not same")
	// 	}
	// }

	return nil
}

// Exports is the export table of this module.
//
var Exports = map[string]interface{}{
	"_name": "github.com/topxeq/govcl/vcl",

	"Application": vcl.Application,
	"Clipboard":   vcl.Clipboard,
	"Mouse":       vcl.Mouse,
	"Printer":     vcl.Printer,
	"Screen":      vcl.Screen,

	"InitLCL":                         initLCL,
	"CheckPtr":                        vcl.CheckPtr,
	"CreateResForm":                   vcl.CreateResForm,
	"CreateResFrame":                  vcl.CreateResFrame,
	"DoInit":                          vcl.DoInit,
	"EqualsObject":                    vcl.EqualsObject,
	"ExceptionClass":                  vcl.ExceptionClass,
	"GetLibVersion":                   vcl.GetLibVersion,
	"InputBox":                        vcl.InputBox,
	"InputQuery":                      vcl.InputQuery,
	"LclLoaded":                       vcl.LclLoaded,
	"MessageDlg":                      vcl.MessageDlg,
	"RegisterExtEventCallback":        vcl.RegisterExtEventCallback,
	"RegisterFormResource":            vcl.RegisterFormResource,
	"RunApp":                          vcl.RunApp,
	"SelectDirectory1":                vcl.SelectDirectory1,
	"SelectDirectory2":                vcl.SelectDirectory2,
	"SelectDirectory3":                vcl.SelectDirectory3,
	"ShowMessage":                     vcl.ShowMessage,
	"ShowMessageFmt":                  vcl.ShowMessageFmt,
	"TActionClass":                    vcl.TActionClass,
	"TActionListClass":                vcl.TActionListClass,
	"TAnchorSideClass":                vcl.TAnchorSideClass,
	"TApplicationClass":               vcl.TApplicationClass,
	"TBevelClass":                     vcl.TBevelClass,
	"TBitBtnClass":                    vcl.TBitBtnClass,
	"TBitmapClass":                    vcl.TBitmapClass,
	"TBoundLabelClass":                vcl.TBoundLabelClass,
	"TBrushClass":                     vcl.TBrushClass,
	"TButtonClass":                    vcl.TButtonClass,
	"TCanvasClass":                    vcl.TCanvasClass,
	"TCheckBoxClass":                  vcl.TCheckBoxClass,
	"TCheckListBoxClass":              vcl.TCheckListBoxClass,
	"TClipboardClass":                 vcl.TClipboardClass,
	"TCollectionClass":                vcl.TCollectionClass,
	"TCollectionItemClass":            vcl.TCollectionItemClass,
	"TColorBoxClass":                  vcl.TColorBoxClass,
	"TColorDialogClass":               vcl.TColorDialogClass,
	"TColorListBoxClass":              vcl.TColorListBoxClass,
	"TComboBoxClass":                  vcl.TComboBoxClass,
	"TComboBoxExClass":                vcl.TComboBoxExClass,
	"TComboExItemClass":               vcl.TComboExItemClass,
	"TComboExItemsClass":              vcl.TComboExItemsClass,
	"TComponentClass":                 vcl.TComponentClass,
	"TControlBorderSpacingClass":      vcl.TControlBorderSpacingClass,
	"TControlChildSizingClass":        vcl.TControlChildSizingClass,
	"TControlClass":                   vcl.TControlClass,
	"TControlScrollBarClass":          vcl.TControlScrollBarClass,
	"TCoolBandClass":                  vcl.TCoolBandClass,
	"TCoolBandsClass":                 vcl.TCoolBandsClass,
	"TCoolBarClass":                   vcl.TCoolBarClass,
	"TDateTimePickerClass":            vcl.TDateTimePickerClass,
	"TDragDockObjectClass":            vcl.TDragDockObjectClass,
	"TDragObjectClass":                vcl.TDragObjectClass,
	"TDrawGridClass":                  vcl.TDrawGridClass,
	"TEditClass":                      vcl.TEditClass,
	"TFindDialogClass":                vcl.TFindDialogClass,
	"TFlowPanelClass":                 vcl.TFlowPanelClass,
	"TFontClass":                      vcl.TFontClass,
	"TFontDialogClass":                vcl.TFontDialogClass,
	"TFormClass":                      vcl.TFormClass,
	"TFrameClass":                     vcl.TFrameClass,
	"TGIFImageClass":                  vcl.TGIFImageClass,
	"TGaugeClass":                     vcl.TGaugeClass,
	"TGraphicClass":                   vcl.TGraphicClass,
	"TGroupBoxClass":                  vcl.TGroupBoxClass,
	"THeaderControlClass":             vcl.THeaderControlClass,
	"THeaderSectionClass":             vcl.THeaderSectionClass,
	"THeaderSectionsClass":            vcl.THeaderSectionsClass,
	"TIconClass":                      vcl.TIconClass,
	"TIconOptionsClass":               vcl.TIconOptionsClass,
	"TImageButtonClass":               vcl.TImageButtonClass,
	"TImageClass":                     vcl.TImageClass,
	"TImageListClass":                 vcl.TImageListClass,
	"TIniFileClass":                   vcl.TIniFileClass,
	"TJPEGImageClass":                 vcl.TJPEGImageClass,
	"TLabelClass":                     vcl.TLabelClass,
	"TLabeledEditClass":               vcl.TLabeledEditClass,
	"TLinkLabelClass":                 vcl.TLinkLabelClass,
	"TListBoxClass":                   vcl.TListBoxClass,
	"TListClass":                      vcl.TListClass,
	"TListColumnClass":                vcl.TListColumnClass,
	"TListColumnsClass":               vcl.TListColumnsClass,
	"TListItemClass":                  vcl.TListItemClass,
	"TListItemsClass":                 vcl.TListItemsClass,
	"TListViewClass":                  vcl.TListViewClass,
	"TMainMenuClass":                  vcl.TMainMenuClass,
	"TMaskEditClass":                  vcl.TMaskEditClass,
	"TMemoClass":                      vcl.TMemoClass,
	"TMemoryStreamClass":              vcl.TMemoryStreamClass,
	"TMenuItemClass":                  vcl.TMenuItemClass,
	"TMiniWebviewClass":               vcl.TMiniWebviewClass,
	"TMonitorClass":                   vcl.TMonitorClass,
	"TMonthCalendarClass":             vcl.TMonthCalendarClass,
	"TMouseClass":                     vcl.TMouseClass,
	"TObjectClass":                    vcl.TObjectClass,
	"TOpenDialogClass":                vcl.TOpenDialogClass,
	"TOpenPictureDialogClass":         vcl.TOpenPictureDialogClass,
	"TPageControlClass":               vcl.TPageControlClass,
	"TPageSetupDialogClass":           vcl.TPageSetupDialogClass,
	"TPaintBoxClass":                  vcl.TPaintBoxClass,
	"TPanelClass":                     vcl.TPanelClass,
	"TParaAttributesClass":            vcl.TParaAttributesClass,
	"TPenClass":                       vcl.TPenClass,
	"TPictureClass":                   vcl.TPictureClass,
	"TPngImageClass":                  vcl.TPngImageClass,
	"TPopupMenuClass":                 vcl.TPopupMenuClass,
	"TPrintDialogClass":               vcl.TPrintDialogClass,
	"TPrinterClass":                   vcl.TPrinterClass,
	"TPrinterSetupDialogClass":        vcl.TPrinterSetupDialogClass,
	"TProgressBarClass":               vcl.TProgressBarClass,
	"TRadioButtonClass":               vcl.TRadioButtonClass,
	"TRadioGroupClass":                vcl.TRadioGroupClass,
	"TRegistryClass":                  vcl.TRegistryClass,
	"TReplaceDialogClass":             vcl.TReplaceDialogClass,
	"TRichEditClass":                  vcl.TRichEditClass,
	"TSaveDialogClass":                vcl.TSaveDialogClass,
	"TSavePictureDialogClass":         vcl.TSavePictureDialogClass,
	"TScreenClass":                    vcl.TScreenClass,
	"TScrollBarClass":                 vcl.TScrollBarClass,
	"TScrollBoxClass":                 vcl.TScrollBoxClass,
	"TSelectDirectoryDialogClass":     vcl.TSelectDirectoryDialogClass,
	"TShapeClass":                     vcl.TShapeClass,
	"TSizeConstraintsClass":           vcl.TSizeConstraintsClass,
	"TSpeedButtonClass":               vcl.TSpeedButtonClass,
	"TSpinEditClass":                  vcl.TSpinEditClass,
	"TSplitterClass":                  vcl.TSplitterClass,
	"TStaticTextClass":                vcl.TStaticTextClass,
	"TStatusBarClass":                 vcl.TStatusBarClass,
	"TStatusPanelClass":               vcl.TStatusPanelClass,
	"TStatusPanelsClass":              vcl.TStatusPanelsClass,
	"TStringGridClass":                vcl.TStringGridClass,
	"TStringListClass":                vcl.TStringListClass,
	"TStringsClass":                   vcl.TStringsClass,
	"TTabSheetClass":                  vcl.TTabSheetClass,
	"TTaskDialogBaseButtonItemClass":  vcl.TTaskDialogBaseButtonItemClass,
	"TTaskDialogButtonItemClass":      vcl.TTaskDialogButtonItemClass,
	"TTaskDialogButtonsClass":         vcl.TTaskDialogButtonsClass,
	"TTaskDialogClass":                vcl.TTaskDialogClass,
	"TTaskDialogRadioButtonItemClass": vcl.TTaskDialogRadioButtonItemClass,
	"TTextAttributesClass":            vcl.TTextAttributesClass,
	"TTimerClass":                     vcl.TTimerClass,
	"TToolBarClass":                   vcl.TToolBarClass,
	"TToolButtonClass":                vcl.TToolButtonClass,
	"TTrackBarClass":                  vcl.TTrackBarClass,
	"TTrayIconClass":                  vcl.TTrayIconClass,
	"TTreeNodeClass":                  vcl.TTreeNodeClass,
	"TTreeNodesClass":                 vcl.TTreeNodesClass,
	"TTreeViewClass":                  vcl.TTreeViewClass,
	"TUpDownClass":                    vcl.TUpDownClass,
	"TValueListEditorClass":           vcl.TValueListEditorClass,
	"TWinControlClass":                vcl.TWinControlClass,
	"TXButtonClass":                   vcl.TXButtonClass,
	"ThreadSync":                      vcl.ThreadSync,

	"AsException":                                vcl.AsException,
	"ExceptionFromInst":                          vcl.ExceptionFromInst,
	"ExceptionFromObj":                           vcl.ExceptionFromObj,
	"ExceptionFromUnsafePointer":                 vcl.ExceptionFromUnsafePointer,
	"ActionFromInst":                             vcl.ActionFromInst,
	"ActionFromObj":                              vcl.ActionFromObj,
	"ActionFromUnsafePointer":                    vcl.ActionFromUnsafePointer,
	"AsAction":                                   vcl.AsAction,
	"NewAction":                                  vcl.NewAction,
	"ActionListFromInst":                         vcl.ActionListFromInst,
	"ActionListFromObj":                          vcl.ActionListFromObj,
	"ActionListFromUnsafePointer":                vcl.ActionListFromUnsafePointer,
	"AsActionList":                               vcl.AsActionList,
	"NewActionList":                              vcl.NewActionList,
	"AnchorSideFromInst":                         vcl.AnchorSideFromInst,
	"AnchorSideFromObj":                          vcl.AnchorSideFromObj,
	"AnchorSideFromUnsafePointer":                vcl.AnchorSideFromUnsafePointer,
	"AsAnchorSide":                               vcl.AsAnchorSide,
	"ApplicationFromInst":                        vcl.ApplicationFromInst,
	"ApplicationFromObj":                         vcl.ApplicationFromObj,
	"ApplicationFromUnsafePointer":               vcl.ApplicationFromUnsafePointer,
	"AsApplication":                              vcl.AsApplication,
	"NewApplication":                             vcl.NewApplication,
	"AsBevel":                                    vcl.AsBevel,
	"BevelFromInst":                              vcl.BevelFromInst,
	"BevelFromObj":                               vcl.BevelFromObj,
	"BevelFromUnsafePointer":                     vcl.BevelFromUnsafePointer,
	"NewBevel":                                   vcl.NewBevel,
	"AsBitBtn":                                   vcl.AsBitBtn,
	"BitBtnFromInst":                             vcl.BitBtnFromInst,
	"BitBtnFromObj":                              vcl.BitBtnFromObj,
	"BitBtnFromUnsafePointer":                    vcl.BitBtnFromUnsafePointer,
	"NewBitBtn":                                  vcl.NewBitBtn,
	"AsBitmap":                                   vcl.AsBitmap,
	"BitmapFromInst":                             vcl.BitmapFromInst,
	"BitmapFromObj":                              vcl.BitmapFromObj,
	"BitmapFromUnsafePointer":                    vcl.BitmapFromUnsafePointer,
	"NewBitmap":                                  vcl.NewBitmap,
	"AsBoundLabel":                               vcl.AsBoundLabel,
	"BoundLabelFromInst":                         vcl.BoundLabelFromInst,
	"BoundLabelFromObj":                          vcl.BoundLabelFromObj,
	"BoundLabelFromUnsafePointer":                vcl.BoundLabelFromUnsafePointer,
	"NewBoundLabel":                              vcl.NewBoundLabel,
	"AsBrush":                                    vcl.AsBrush,
	"BrushFromInst":                              vcl.BrushFromInst,
	"BrushFromObj":                               vcl.BrushFromObj,
	"BrushFromUnsafePointer":                     vcl.BrushFromUnsafePointer,
	"NewBrush":                                   vcl.NewBrush,
	"AsButton":                                   vcl.AsButton,
	"ButtonFromInst":                             vcl.ButtonFromInst,
	"ButtonFromObj":                              vcl.ButtonFromObj,
	"ButtonFromUnsafePointer":                    vcl.ButtonFromUnsafePointer,
	"NewButton":                                  vcl.NewButton,
	"AsCanvas":                                   vcl.AsCanvas,
	"CanvasFromInst":                             vcl.CanvasFromInst,
	"CanvasFromObj":                              vcl.CanvasFromObj,
	"CanvasFromUnsafePointer":                    vcl.CanvasFromUnsafePointer,
	"NewCanvas":                                  vcl.NewCanvas,
	"AsCheckBox":                                 vcl.AsCheckBox,
	"CheckBoxFromInst":                           vcl.CheckBoxFromInst,
	"CheckBoxFromObj":                            vcl.CheckBoxFromObj,
	"CheckBoxFromUnsafePointer":                  vcl.CheckBoxFromUnsafePointer,
	"NewCheckBox":                                vcl.NewCheckBox,
	"AsCheckListBox":                             vcl.AsCheckListBox,
	"CheckListBoxFromInst":                       vcl.CheckListBoxFromInst,
	"CheckListBoxFromObj":                        vcl.CheckListBoxFromObj,
	"CheckListBoxFromUnsafePointer":              vcl.CheckListBoxFromUnsafePointer,
	"NewCheckListBox":                            vcl.NewCheckListBox,
	"AsClipboard":                                vcl.AsClipboard,
	"ClipboardFromInst":                          vcl.ClipboardFromInst,
	"ClipboardFromObj":                           vcl.ClipboardFromObj,
	"ClipboardFromUnsafePointer":                 vcl.ClipboardFromUnsafePointer,
	"NewClipboard":                               vcl.NewClipboard,
	"SetClipboard":                               vcl.SetClipboard,
	"AsCollection":                               vcl.AsCollection,
	"CollectionFromInst":                         vcl.CollectionFromInst,
	"CollectionFromObj":                          vcl.CollectionFromObj,
	"CollectionFromUnsafePointer":                vcl.CollectionFromUnsafePointer,
	"NewCollection":                              vcl.NewCollection,
	"AsCollectionItem":                           vcl.AsCollectionItem,
	"CollectionItemFromInst":                     vcl.CollectionItemFromInst,
	"CollectionItemFromObj":                      vcl.CollectionItemFromObj,
	"CollectionItemFromUnsafePointer":            vcl.CollectionItemFromUnsafePointer,
	"NewCollectionItem":                          vcl.NewCollectionItem,
	"AsColorBox":                                 vcl.AsColorBox,
	"ColorBoxFromInst":                           vcl.ColorBoxFromInst,
	"ColorBoxFromObj":                            vcl.ColorBoxFromObj,
	"ColorBoxFromUnsafePointer":                  vcl.ColorBoxFromUnsafePointer,
	"NewColorBox":                                vcl.NewColorBox,
	"AsColorDialog":                              vcl.AsColorDialog,
	"ColorDialogFromInst":                        vcl.ColorDialogFromInst,
	"ColorDialogFromObj":                         vcl.ColorDialogFromObj,
	"ColorDialogFromUnsafePointer":               vcl.ColorDialogFromUnsafePointer,
	"NewColorDialog":                             vcl.NewColorDialog,
	"AsColorListBox":                             vcl.AsColorListBox,
	"ColorListBoxFromInst":                       vcl.ColorListBoxFromInst,
	"ColorListBoxFromObj":                        vcl.ColorListBoxFromObj,
	"ColorListBoxFromUnsafePointer":              vcl.ColorListBoxFromUnsafePointer,
	"NewColorListBox":                            vcl.NewColorListBox,
	"AsComboBox":                                 vcl.AsComboBox,
	"ComboBoxFromInst":                           vcl.ComboBoxFromInst,
	"ComboBoxFromObj":                            vcl.ComboBoxFromObj,
	"ComboBoxFromUnsafePointer":                  vcl.ComboBoxFromUnsafePointer,
	"NewComboBox":                                vcl.NewComboBox,
	"AsComboBoxEx":                               vcl.AsComboBoxEx,
	"ComboBoxExFromInst":                         vcl.ComboBoxExFromInst,
	"ComboBoxExFromObj":                          vcl.ComboBoxExFromObj,
	"ComboBoxExFromUnsafePointer":                vcl.ComboBoxExFromUnsafePointer,
	"NewComboBoxEx":                              vcl.NewComboBoxEx,
	"AsComboExItem":                              vcl.AsComboExItem,
	"ComboExItemFromInst":                        vcl.ComboExItemFromInst,
	"ComboExItemFromObj":                         vcl.ComboExItemFromObj,
	"ComboExItemFromUnsafePointer":               vcl.ComboExItemFromUnsafePointer,
	"AsComboExItems":                             vcl.AsComboExItems,
	"ComboExItemsFromInst":                       vcl.ComboExItemsFromInst,
	"ComboExItemsFromObj":                        vcl.ComboExItemsFromObj,
	"ComboExItemsFromUnsafePointer":              vcl.ComboExItemsFromUnsafePointer,
	"AsComponent":                                vcl.AsComponent,
	"ComponentFromInst":                          vcl.ComponentFromInst,
	"ComponentFromObj":                           vcl.ComponentFromObj,
	"ComponentFromUnsafePointer":                 vcl.ComponentFromUnsafePointer,
	"NewComponent":                               vcl.NewComponent,
	"AsControl":                                  vcl.AsControl,
	"ControlFromInst":                            vcl.ControlFromInst,
	"ControlFromObj":                             vcl.ControlFromObj,
	"ControlFromUnsafePointer":                   vcl.ControlFromUnsafePointer,
	"NewControl":                                 vcl.NewControl,
	"AsControlBorderSpacing":                     vcl.AsControlBorderSpacing,
	"ControlBorderSpacingFromInst":               vcl.ControlBorderSpacingFromInst,
	"ControlBorderSpacingFromObj":                vcl.ControlBorderSpacingFromObj,
	"ControlBorderSpacingFromUnsafePointer":      vcl.ControlBorderSpacingFromUnsafePointer,
	"AsControlChildSizing":                       vcl.AsControlChildSizing,
	"ControlChildSizingFromInst":                 vcl.ControlChildSizingFromInst,
	"ControlChildSizingFromObj":                  vcl.ControlChildSizingFromObj,
	"ControlChildSizingFromUnsafePointer":        vcl.ControlChildSizingFromUnsafePointer,
	"AsControlScrollBar":                         vcl.AsControlScrollBar,
	"ControlScrollBarFromInst":                   vcl.ControlScrollBarFromInst,
	"ControlScrollBarFromObj":                    vcl.ControlScrollBarFromObj,
	"ControlScrollBarFromUnsafePointer":          vcl.ControlScrollBarFromUnsafePointer,
	"AsCoolBand":                                 vcl.AsCoolBand,
	"CoolBandFromInst":                           vcl.CoolBandFromInst,
	"CoolBandFromObj":                            vcl.CoolBandFromObj,
	"CoolBandFromUnsafePointer":                  vcl.CoolBandFromUnsafePointer,
	"NewCoolBand":                                vcl.NewCoolBand,
	"AsCoolBands":                                vcl.AsCoolBands,
	"CoolBandsFromInst":                          vcl.CoolBandsFromInst,
	"CoolBandsFromObj":                           vcl.CoolBandsFromObj,
	"CoolBandsFromUnsafePointer":                 vcl.CoolBandsFromUnsafePointer,
	"NewCoolBands":                               vcl.NewCoolBands,
	"AsCoolBar":                                  vcl.AsCoolBar,
	"CoolBarFromInst":                            vcl.CoolBarFromInst,
	"CoolBarFromObj":                             vcl.CoolBarFromObj,
	"CoolBarFromUnsafePointer":                   vcl.CoolBarFromUnsafePointer,
	"NewCoolBar":                                 vcl.NewCoolBar,
	"AsDateTimePicker":                           vcl.AsDateTimePicker,
	"DateTimePickerFromInst":                     vcl.DateTimePickerFromInst,
	"DateTimePickerFromObj":                      vcl.DateTimePickerFromObj,
	"DateTimePickerFromUnsafePointer":            vcl.DateTimePickerFromUnsafePointer,
	"NewDateTimePicker":                          vcl.NewDateTimePicker,
	"AsDragDockObject":                           vcl.AsDragDockObject,
	"DragDockObjectFromInst":                     vcl.DragDockObjectFromInst,
	"DragDockObjectFromObj":                      vcl.DragDockObjectFromObj,
	"DragDockObjectFromUnsafePointer":            vcl.DragDockObjectFromUnsafePointer,
	"NewDragDockObject":                          vcl.NewDragDockObject,
	"AsDragObject":                               vcl.AsDragObject,
	"DragObjectFromInst":                         vcl.DragObjectFromInst,
	"DragObjectFromObj":                          vcl.DragObjectFromObj,
	"DragObjectFromUnsafePointer":                vcl.DragObjectFromUnsafePointer,
	"NewDragObject":                              vcl.NewDragObject,
	"AsDrawGrid":                                 vcl.AsDrawGrid,
	"DrawGridFromInst":                           vcl.DrawGridFromInst,
	"DrawGridFromObj":                            vcl.DrawGridFromObj,
	"DrawGridFromUnsafePointer":                  vcl.DrawGridFromUnsafePointer,
	"NewDrawGrid":                                vcl.NewDrawGrid,
	"AsEdit":                                     vcl.AsEdit,
	"EditFromInst":                               vcl.EditFromInst,
	"EditFromObj":                                vcl.EditFromObj,
	"EditFromUnsafePointer":                      vcl.EditFromUnsafePointer,
	"NewEdit":                                    vcl.NewEdit,
	"AsFindDialog":                               vcl.AsFindDialog,
	"FindDialogFromInst":                         vcl.FindDialogFromInst,
	"FindDialogFromObj":                          vcl.FindDialogFromObj,
	"FindDialogFromUnsafePointer":                vcl.FindDialogFromUnsafePointer,
	"NewFindDialog":                              vcl.NewFindDialog,
	"AsFlowPanel":                                vcl.AsFlowPanel,
	"FlowPanelFromInst":                          vcl.FlowPanelFromInst,
	"FlowPanelFromObj":                           vcl.FlowPanelFromObj,
	"FlowPanelFromUnsafePointer":                 vcl.FlowPanelFromUnsafePointer,
	"NewFlowPanel":                               vcl.NewFlowPanel,
	"AsFont":                                     vcl.AsFont,
	"FontFromInst":                               vcl.FontFromInst,
	"FontFromObj":                                vcl.FontFromObj,
	"FontFromUnsafePointer":                      vcl.FontFromUnsafePointer,
	"NewFont":                                    vcl.NewFont,
	"AsFontDialog":                               vcl.AsFontDialog,
	"FontDialogFromInst":                         vcl.FontDialogFromInst,
	"FontDialogFromObj":                          vcl.FontDialogFromObj,
	"FontDialogFromUnsafePointer":                vcl.FontDialogFromUnsafePointer,
	"NewFontDialog":                              vcl.NewFontDialog,
	"AsForm":                                     vcl.AsForm,
	"FormFromInst":                               vcl.FormFromInst,
	"FormFromObj":                                vcl.FormFromObj,
	"FormFromUnsafePointer":                      vcl.FormFromUnsafePointer,
	"NewForm":                                    vcl.NewForm,
	"AsFrame":                                    vcl.AsFrame,
	"FrameFromInst":                              vcl.FrameFromInst,
	"FrameFromObj":                               vcl.FrameFromObj,
	"FrameFromUnsafePointer":                     vcl.FrameFromUnsafePointer,
	"NewFrame":                                   vcl.NewFrame,
	"AsGIFImage":                                 vcl.AsGIFImage,
	"GIFImageFromInst":                           vcl.GIFImageFromInst,
	"GIFImageFromObj":                            vcl.GIFImageFromObj,
	"GIFImageFromUnsafePointer":                  vcl.GIFImageFromUnsafePointer,
	"NewGIFImage":                                vcl.NewGIFImage,
	"AsGauge":                                    vcl.AsGauge,
	"GaugeFromInst":                              vcl.GaugeFromInst,
	"GaugeFromObj":                               vcl.GaugeFromObj,
	"GaugeFromUnsafePointer":                     vcl.GaugeFromUnsafePointer,
	"NewGauge":                                   vcl.NewGauge,
	"AsGraphic":                                  vcl.AsGraphic,
	"GraphicFromInst":                            vcl.GraphicFromInst,
	"GraphicFromObj":                             vcl.GraphicFromObj,
	"GraphicFromUnsafePointer":                   vcl.GraphicFromUnsafePointer,
	"NewGraphic":                                 vcl.NewGraphic,
	"AsGroupBox":                                 vcl.AsGroupBox,
	"GroupBoxFromInst":                           vcl.GroupBoxFromInst,
	"GroupBoxFromObj":                            vcl.GroupBoxFromObj,
	"GroupBoxFromUnsafePointer":                  vcl.GroupBoxFromUnsafePointer,
	"NewGroupBox":                                vcl.NewGroupBox,
	"AsHeaderControl":                            vcl.AsHeaderControl,
	"HeaderControlFromInst":                      vcl.HeaderControlFromInst,
	"HeaderControlFromObj":                       vcl.HeaderControlFromObj,
	"HeaderControlFromUnsafePointer":             vcl.HeaderControlFromUnsafePointer,
	"NewHeaderControl":                           vcl.NewHeaderControl,
	"AsHeaderSection":                            vcl.AsHeaderSection,
	"HeaderSectionFromInst":                      vcl.HeaderSectionFromInst,
	"HeaderSectionFromObj":                       vcl.HeaderSectionFromObj,
	"HeaderSectionFromUnsafePointer":             vcl.HeaderSectionFromUnsafePointer,
	"NewHeaderSection":                           vcl.NewHeaderSection,
	"AsHeaderSections":                           vcl.AsHeaderSections,
	"HeaderSectionsFromInst":                     vcl.HeaderSectionsFromInst,
	"HeaderSectionsFromObj":                      vcl.HeaderSectionsFromObj,
	"HeaderSectionsFromUnsafePointer":            vcl.HeaderSectionsFromUnsafePointer,
	"NewHeaderSections":                          vcl.NewHeaderSections,
	"AsIcon":                                     vcl.AsIcon,
	"IconFromInst":                               vcl.IconFromInst,
	"IconFromObj":                                vcl.IconFromObj,
	"IconFromUnsafePointer":                      vcl.IconFromUnsafePointer,
	"NewIcon":                                    vcl.NewIcon,
	"AsIconOptions":                              vcl.AsIconOptions,
	"IconOptionsFromInst":                        vcl.IconOptionsFromInst,
	"IconOptionsFromObj":                         vcl.IconOptionsFromObj,
	"IconOptionsFromUnsafePointer":               vcl.IconOptionsFromUnsafePointer,
	"AsImage":                                    vcl.AsImage,
	"ImageFromInst":                              vcl.ImageFromInst,
	"ImageFromObj":                               vcl.ImageFromObj,
	"ImageFromUnsafePointer":                     vcl.ImageFromUnsafePointer,
	"NewImage":                                   vcl.NewImage,
	"AsImageButton":                              vcl.AsImageButton,
	"ImageButtonFromInst":                        vcl.ImageButtonFromInst,
	"ImageButtonFromObj":                         vcl.ImageButtonFromObj,
	"ImageButtonFromUnsafePointer":               vcl.ImageButtonFromUnsafePointer,
	"NewImageButton":                             vcl.NewImageButton,
	"AsImageList":                                vcl.AsImageList,
	"ImageListFromInst":                          vcl.ImageListFromInst,
	"ImageListFromObj":                           vcl.ImageListFromObj,
	"ImageListFromUnsafePointer":                 vcl.ImageListFromUnsafePointer,
	"NewImageList":                               vcl.NewImageList,
	"AsIniFile":                                  vcl.AsIniFile,
	"IniFileFromInst":                            vcl.IniFileFromInst,
	"IniFileFromObj":                             vcl.IniFileFromObj,
	"IniFileFromUnsafePointer":                   vcl.IniFileFromUnsafePointer,
	"NewIniFile":                                 vcl.NewIniFile,
	"AsJPEGImage":                                vcl.AsJPEGImage,
	"JPEGImageFromInst":                          vcl.JPEGImageFromInst,
	"JPEGImageFromObj":                           vcl.JPEGImageFromObj,
	"JPEGImageFromUnsafePointer":                 vcl.JPEGImageFromUnsafePointer,
	"NewJPEGImage":                               vcl.NewJPEGImage,
	"AsLabel":                                    vcl.AsLabel,
	"LabelFromInst":                              vcl.LabelFromInst,
	"LabelFromObj":                               vcl.LabelFromObj,
	"LabelFromUnsafePointer":                     vcl.LabelFromUnsafePointer,
	"NewLabel":                                   vcl.NewLabel,
	"AsLabeledEdit":                              vcl.AsLabeledEdit,
	"LabeledEditFromInst":                        vcl.LabeledEditFromInst,
	"LabeledEditFromObj":                         vcl.LabeledEditFromObj,
	"LabeledEditFromUnsafePointer":               vcl.LabeledEditFromUnsafePointer,
	"NewLabeledEdit":                             vcl.NewLabeledEdit,
	"AsLinkLabel":                                vcl.AsLinkLabel,
	"LinkLabelFromInst":                          vcl.LinkLabelFromInst,
	"LinkLabelFromObj":                           vcl.LinkLabelFromObj,
	"LinkLabelFromUnsafePointer":                 vcl.LinkLabelFromUnsafePointer,
	"NewLinkLabel":                               vcl.NewLinkLabel,
	"AsList":                                     vcl.AsList,
	"ListFromInst":                               vcl.ListFromInst,
	"ListFromObj":                                vcl.ListFromObj,
	"ListFromUnsafePointer":                      vcl.ListFromUnsafePointer,
	"NewList":                                    vcl.NewList,
	"AsListBox":                                  vcl.AsListBox,
	"ListBoxFromInst":                            vcl.ListBoxFromInst,
	"ListBoxFromObj":                             vcl.ListBoxFromObj,
	"ListBoxFromUnsafePointer":                   vcl.ListBoxFromUnsafePointer,
	"NewListBox":                                 vcl.NewListBox,
	"AsListColumn":                               vcl.AsListColumn,
	"ListColumnFromInst":                         vcl.ListColumnFromInst,
	"ListColumnFromObj":                          vcl.ListColumnFromObj,
	"ListColumnFromUnsafePointer":                vcl.ListColumnFromUnsafePointer,
	"NewListColumn":                              vcl.NewListColumn,
	"AsListColumns":                              vcl.AsListColumns,
	"ListColumnsFromInst":                        vcl.ListColumnsFromInst,
	"ListColumnsFromObj":                         vcl.ListColumnsFromObj,
	"ListColumnsFromUnsafePointer":               vcl.ListColumnsFromUnsafePointer,
	"NewListColumns":                             vcl.NewListColumns,
	"AsListItem":                                 vcl.AsListItem,
	"ListItemFromInst":                           vcl.ListItemFromInst,
	"ListItemFromObj":                            vcl.ListItemFromObj,
	"ListItemFromUnsafePointer":                  vcl.ListItemFromUnsafePointer,
	"NewListItem":                                vcl.NewListItem,
	"AsListItems":                                vcl.AsListItems,
	"ListItemsFromInst":                          vcl.ListItemsFromInst,
	"ListItemsFromObj":                           vcl.ListItemsFromObj,
	"ListItemsFromUnsafePointer":                 vcl.ListItemsFromUnsafePointer,
	"NewListItems":                               vcl.NewListItems,
	"AsListView":                                 vcl.AsListView,
	"ListViewFromInst":                           vcl.ListViewFromInst,
	"ListViewFromObj":                            vcl.ListViewFromObj,
	"ListViewFromUnsafePointer":                  vcl.ListViewFromUnsafePointer,
	"NewListView":                                vcl.NewListView,
	"AsMainMenu":                                 vcl.AsMainMenu,
	"MainMenuFromInst":                           vcl.MainMenuFromInst,
	"MainMenuFromObj":                            vcl.MainMenuFromObj,
	"MainMenuFromUnsafePointer":                  vcl.MainMenuFromUnsafePointer,
	"NewMainMenu":                                vcl.NewMainMenu,
	"AsMaskEdit":                                 vcl.AsMaskEdit,
	"MaskEditFromInst":                           vcl.MaskEditFromInst,
	"MaskEditFromObj":                            vcl.MaskEditFromObj,
	"MaskEditFromUnsafePointer":                  vcl.MaskEditFromUnsafePointer,
	"NewMaskEdit":                                vcl.NewMaskEdit,
	"AsMemo":                                     vcl.AsMemo,
	"MemoFromInst":                               vcl.MemoFromInst,
	"MemoFromObj":                                vcl.MemoFromObj,
	"MemoFromUnsafePointer":                      vcl.MemoFromUnsafePointer,
	"NewMemo":                                    vcl.NewMemo,
	"AsMemoryStream":                             vcl.AsMemoryStream,
	"MemoryStreamFromInst":                       vcl.MemoryStreamFromInst,
	"MemoryStreamFromObj":                        vcl.MemoryStreamFromObj,
	"MemoryStreamFromUnsafePointer":              vcl.MemoryStreamFromUnsafePointer,
	"NewMemoryStream":                            vcl.NewMemoryStream,
	"NewMemoryStreamFromBytes":                   vcl.NewMemoryStreamFromBytes,
	"AsMenuItem":                                 vcl.AsMenuItem,
	"MenuItemFromInst":                           vcl.MenuItemFromInst,
	"MenuItemFromObj":                            vcl.MenuItemFromObj,
	"MenuItemFromUnsafePointer":                  vcl.MenuItemFromUnsafePointer,
	"NewMenuItem":                                vcl.NewMenuItem,
	"AsMiniWebview":                              vcl.AsMiniWebview,
	"MiniWebviewFromInst":                        vcl.MiniWebviewFromInst,
	"MiniWebviewFromObj":                         vcl.MiniWebviewFromObj,
	"MiniWebviewFromUnsafePointer":               vcl.MiniWebviewFromUnsafePointer,
	"NewMiniWebview":                             vcl.NewMiniWebview,
	"AsMonitor":                                  vcl.AsMonitor,
	"MonitorFromInst":                            vcl.MonitorFromInst,
	"MonitorFromObj":                             vcl.MonitorFromObj,
	"MonitorFromUnsafePointer":                   vcl.MonitorFromUnsafePointer,
	"NewMonitor":                                 vcl.NewMonitor,
	"AsMonthCalendar":                            vcl.AsMonthCalendar,
	"MonthCalendarFromInst":                      vcl.MonthCalendarFromInst,
	"MonthCalendarFromObj":                       vcl.MonthCalendarFromObj,
	"MonthCalendarFromUnsafePointer":             vcl.MonthCalendarFromUnsafePointer,
	"NewMonthCalendar":                           vcl.NewMonthCalendar,
	"AsMouse":                                    vcl.AsMouse,
	"MouseFromInst":                              vcl.MouseFromInst,
	"MouseFromObj":                               vcl.MouseFromObj,
	"MouseFromUnsafePointer":                     vcl.MouseFromUnsafePointer,
	"NewMouse":                                   vcl.NewMouse,
	"AsObject":                                   vcl.AsObject,
	"NewObject":                                  vcl.NewObject,
	"ObjectFromInst":                             vcl.ObjectFromInst,
	"ObjectFromObj":                              vcl.ObjectFromObj,
	"ObjectFromUnsafePointer":                    vcl.ObjectFromUnsafePointer,
	"AsOpenDialog":                               vcl.AsOpenDialog,
	"NewOpenDialog":                              vcl.NewOpenDialog,
	"OpenDialogFromInst":                         vcl.OpenDialogFromInst,
	"OpenDialogFromObj":                          vcl.OpenDialogFromObj,
	"OpenDialogFromUnsafePointer":                vcl.OpenDialogFromUnsafePointer,
	"AsOpenPictureDialog":                        vcl.AsOpenPictureDialog,
	"NewOpenPictureDialog":                       vcl.NewOpenPictureDialog,
	"OpenPictureDialogFromInst":                  vcl.OpenPictureDialogFromInst,
	"OpenPictureDialogFromObj":                   vcl.OpenPictureDialogFromObj,
	"OpenPictureDialogFromUnsafePointer":         vcl.OpenPictureDialogFromUnsafePointer,
	"AsPageControl":                              vcl.AsPageControl,
	"NewPageControl":                             vcl.NewPageControl,
	"PageControlFromInst":                        vcl.PageControlFromInst,
	"PageControlFromObj":                         vcl.PageControlFromObj,
	"PageControlFromUnsafePointer":               vcl.PageControlFromUnsafePointer,
	"AsPageSetupDialog":                          vcl.AsPageSetupDialog,
	"NewPageSetupDialog":                         vcl.NewPageSetupDialog,
	"PageSetupDialogFromInst":                    vcl.PageSetupDialogFromInst,
	"PageSetupDialogFromObj":                     vcl.PageSetupDialogFromObj,
	"PageSetupDialogFromUnsafePointer":           vcl.PageSetupDialogFromUnsafePointer,
	"AsPaintBox":                                 vcl.AsPaintBox,
	"NewPaintBox":                                vcl.NewPaintBox,
	"PaintBoxFromInst":                           vcl.PaintBoxFromInst,
	"PaintBoxFromObj":                            vcl.PaintBoxFromObj,
	"PaintBoxFromUnsafePointer":                  vcl.PaintBoxFromUnsafePointer,
	"AsPanel":                                    vcl.AsPanel,
	"NewPanel":                                   vcl.NewPanel,
	"PanelFromInst":                              vcl.PanelFromInst,
	"PanelFromObj":                               vcl.PanelFromObj,
	"PanelFromUnsafePointer":                     vcl.PanelFromUnsafePointer,
	"AsParaAttributes":                           vcl.AsParaAttributes,
	"ParaAttributesFromInst":                     vcl.ParaAttributesFromInst,
	"ParaAttributesFromObj":                      vcl.ParaAttributesFromObj,
	"ParaAttributesFromUnsafePointer":            vcl.ParaAttributesFromUnsafePointer,
	"AsPen":                                      vcl.AsPen,
	"NewPen":                                     vcl.NewPen,
	"PenFromInst":                                vcl.PenFromInst,
	"PenFromObj":                                 vcl.PenFromObj,
	"PenFromUnsafePointer":                       vcl.PenFromUnsafePointer,
	"AsPicture":                                  vcl.AsPicture,
	"NewPicture":                                 vcl.NewPicture,
	"PictureFromInst":                            vcl.PictureFromInst,
	"PictureFromObj":                             vcl.PictureFromObj,
	"PictureFromUnsafePointer":                   vcl.PictureFromUnsafePointer,
	"AsPngImage":                                 vcl.AsPngImage,
	"NewPngImage":                                vcl.NewPngImage,
	"PngImageFromInst":                           vcl.PngImageFromInst,
	"PngImageFromObj":                            vcl.PngImageFromObj,
	"PngImageFromUnsafePointer":                  vcl.PngImageFromUnsafePointer,
	"AsPopupMenu":                                vcl.AsPopupMenu,
	"NewPopupMenu":                               vcl.NewPopupMenu,
	"PopupMenuFromInst":                          vcl.PopupMenuFromInst,
	"PopupMenuFromObj":                           vcl.PopupMenuFromObj,
	"PopupMenuFromUnsafePointer":                 vcl.PopupMenuFromUnsafePointer,
	"AsPrintDialog":                              vcl.AsPrintDialog,
	"NewPrintDialog":                             vcl.NewPrintDialog,
	"PrintDialogFromInst":                        vcl.PrintDialogFromInst,
	"PrintDialogFromObj":                         vcl.PrintDialogFromObj,
	"PrintDialogFromUnsafePointer":               vcl.PrintDialogFromUnsafePointer,
	"AsPrinter":                                  vcl.AsPrinter,
	"NewPrinter":                                 vcl.NewPrinter,
	"PrinterFromInst":                            vcl.PrinterFromInst,
	"PrinterFromObj":                             vcl.PrinterFromObj,
	"PrinterFromUnsafePointer":                   vcl.PrinterFromUnsafePointer,
	"AsPrinterSetupDialog":                       vcl.AsPrinterSetupDialog,
	"NewPrinterSetupDialog":                      vcl.NewPrinterSetupDialog,
	"PrinterSetupDialogFromInst":                 vcl.PrinterSetupDialogFromInst,
	"PrinterSetupDialogFromObj":                  vcl.PrinterSetupDialogFromObj,
	"PrinterSetupDialogFromUnsafePointer":        vcl.PrinterSetupDialogFromUnsafePointer,
	"AsProgressBar":                              vcl.AsProgressBar,
	"NewProgressBar":                             vcl.NewProgressBar,
	"ProgressBarFromInst":                        vcl.ProgressBarFromInst,
	"ProgressBarFromObj":                         vcl.ProgressBarFromObj,
	"ProgressBarFromUnsafePointer":               vcl.ProgressBarFromUnsafePointer,
	"AsRadioButton":                              vcl.AsRadioButton,
	"NewRadioButton":                             vcl.NewRadioButton,
	"RadioButtonFromInst":                        vcl.RadioButtonFromInst,
	"RadioButtonFromObj":                         vcl.RadioButtonFromObj,
	"RadioButtonFromUnsafePointer":               vcl.RadioButtonFromUnsafePointer,
	"AsRadioGroup":                               vcl.AsRadioGroup,
	"NewRadioGroup":                              vcl.NewRadioGroup,
	"RadioGroupFromInst":                         vcl.RadioGroupFromInst,
	"RadioGroupFromObj":                          vcl.RadioGroupFromObj,
	"RadioGroupFromUnsafePointer":                vcl.RadioGroupFromUnsafePointer,
	"AsRegistry":                                 vcl.AsRegistry,
	"NewRegistry":                                vcl.NewRegistry,
	"NewRegistryAllAccess":                       vcl.NewRegistryAllAccess,
	"RegistryFromInst":                           vcl.RegistryFromInst,
	"RegistryFromObj":                            vcl.RegistryFromObj,
	"RegistryFromUnsafePointer":                  vcl.RegistryFromUnsafePointer,
	"AsReplaceDialog":                            vcl.AsReplaceDialog,
	"NewReplaceDialog":                           vcl.NewReplaceDialog,
	"ReplaceDialogFromInst":                      vcl.ReplaceDialogFromInst,
	"ReplaceDialogFromObj":                       vcl.ReplaceDialogFromObj,
	"ReplaceDialogFromUnsafePointer":             vcl.ReplaceDialogFromUnsafePointer,
	"AsRichEdit":                                 vcl.AsRichEdit,
	"NewRichEdit":                                vcl.NewRichEdit,
	"RichEditFromInst":                           vcl.RichEditFromInst,
	"RichEditFromObj":                            vcl.RichEditFromObj,
	"RichEditFromUnsafePointer":                  vcl.RichEditFromUnsafePointer,
	"AsSaveDialog":                               vcl.AsSaveDialog,
	"NewSaveDialog":                              vcl.NewSaveDialog,
	"SaveDialogFromInst":                         vcl.SaveDialogFromInst,
	"SaveDialogFromObj":                          vcl.SaveDialogFromObj,
	"SaveDialogFromUnsafePointer":                vcl.SaveDialogFromUnsafePointer,
	"AsSavePictureDialog":                        vcl.AsSavePictureDialog,
	"NewSavePictureDialog":                       vcl.NewSavePictureDialog,
	"SavePictureDialogFromInst":                  vcl.SavePictureDialogFromInst,
	"SavePictureDialogFromObj":                   vcl.SavePictureDialogFromObj,
	"SavePictureDialogFromUnsafePointer":         vcl.SavePictureDialogFromUnsafePointer,
	"AsScreen":                                   vcl.AsScreen,
	"NewScreen":                                  vcl.NewScreen,
	"ScreenFromInst":                             vcl.ScreenFromInst,
	"ScreenFromObj":                              vcl.ScreenFromObj,
	"ScreenFromUnsafePointer":                    vcl.ScreenFromUnsafePointer,
	"AsScrollBar":                                vcl.AsScrollBar,
	"NewScrollBar":                               vcl.NewScrollBar,
	"ScrollBarFromInst":                          vcl.ScrollBarFromInst,
	"ScrollBarFromObj":                           vcl.ScrollBarFromObj,
	"ScrollBarFromUnsafePointer":                 vcl.ScrollBarFromUnsafePointer,
	"AsScrollBox":                                vcl.AsScrollBox,
	"NewScrollBox":                               vcl.NewScrollBox,
	"ScrollBoxFromInst":                          vcl.ScrollBoxFromInst,
	"ScrollBoxFromObj":                           vcl.ScrollBoxFromObj,
	"ScrollBoxFromUnsafePointer":                 vcl.ScrollBoxFromUnsafePointer,
	"AsSelectDirectoryDialog":                    vcl.AsSelectDirectoryDialog,
	"NewSelectDirectoryDialog":                   vcl.NewSelectDirectoryDialog,
	"SelectDirectoryDialogFromInst":              vcl.SelectDirectoryDialogFromInst,
	"SelectDirectoryDialogFromObj":               vcl.SelectDirectoryDialogFromObj,
	"SelectDirectoryDialogFromUnsafePointer":     vcl.SelectDirectoryDialogFromUnsafePointer,
	"AsShape":                                    vcl.AsShape,
	"NewShape":                                   vcl.NewShape,
	"ShapeFromInst":                              vcl.ShapeFromInst,
	"ShapeFromObj":                               vcl.ShapeFromObj,
	"ShapeFromUnsafePointer":                     vcl.ShapeFromUnsafePointer,
	"AsSizeConstraints":                          vcl.AsSizeConstraints,
	"SizeConstraintsFromInst":                    vcl.SizeConstraintsFromInst,
	"SizeConstraintsFromObj":                     vcl.SizeConstraintsFromObj,
	"SizeConstraintsFromUnsafePointer":           vcl.SizeConstraintsFromUnsafePointer,
	"AsSpeedButton":                              vcl.AsSpeedButton,
	"NewSpeedButton":                             vcl.NewSpeedButton,
	"SpeedButtonFromInst":                        vcl.SpeedButtonFromInst,
	"SpeedButtonFromObj":                         vcl.SpeedButtonFromObj,
	"SpeedButtonFromUnsafePointer":               vcl.SpeedButtonFromUnsafePointer,
	"AsSpinEdit":                                 vcl.AsSpinEdit,
	"NewSpinEdit":                                vcl.NewSpinEdit,
	"SpinEditFromInst":                           vcl.SpinEditFromInst,
	"SpinEditFromObj":                            vcl.SpinEditFromObj,
	"SpinEditFromUnsafePointer":                  vcl.SpinEditFromUnsafePointer,
	"AsSplitter":                                 vcl.AsSplitter,
	"NewSplitter":                                vcl.NewSplitter,
	"SplitterFromInst":                           vcl.SplitterFromInst,
	"SplitterFromObj":                            vcl.SplitterFromObj,
	"SplitterFromUnsafePointer":                  vcl.SplitterFromUnsafePointer,
	"AsStaticText":                               vcl.AsStaticText,
	"NewStaticText":                              vcl.NewStaticText,
	"StaticTextFromInst":                         vcl.StaticTextFromInst,
	"StaticTextFromObj":                          vcl.StaticTextFromObj,
	"StaticTextFromUnsafePointer":                vcl.StaticTextFromUnsafePointer,
	"AsStatusBar":                                vcl.AsStatusBar,
	"NewStatusBar":                               vcl.NewStatusBar,
	"StatusBarFromInst":                          vcl.StatusBarFromInst,
	"StatusBarFromObj":                           vcl.StatusBarFromObj,
	"StatusBarFromUnsafePointer":                 vcl.StatusBarFromUnsafePointer,
	"AsStatusPanel":                              vcl.AsStatusPanel,
	"NewStatusPanel":                             vcl.NewStatusPanel,
	"StatusPanelFromInst":                        vcl.StatusPanelFromInst,
	"StatusPanelFromObj":                         vcl.StatusPanelFromObj,
	"StatusPanelFromUnsafePointer":               vcl.StatusPanelFromUnsafePointer,
	"AsStatusPanels":                             vcl.AsStatusPanels,
	"NewStatusPanels":                            vcl.NewStatusPanels,
	"StatusPanelsFromInst":                       vcl.StatusPanelsFromInst,
	"StatusPanelsFromObj":                        vcl.StatusPanelsFromObj,
	"StatusPanelsFromUnsafePointer":              vcl.StatusPanelsFromUnsafePointer,
	"AsStringGrid":                               vcl.AsStringGrid,
	"NewStringGrid":                              vcl.NewStringGrid,
	"StringGridFromInst":                         vcl.StringGridFromInst,
	"StringGridFromObj":                          vcl.StringGridFromObj,
	"StringGridFromUnsafePointer":                vcl.StringGridFromUnsafePointer,
	"AsStringList":                               vcl.AsStringList,
	"NewStringList":                              vcl.NewStringList,
	"StringListFromInst":                         vcl.StringListFromInst,
	"StringListFromObj":                          vcl.StringListFromObj,
	"StringListFromUnsafePointer":                vcl.StringListFromUnsafePointer,
	"AsStrings":                                  vcl.AsStrings,
	"NewStrings":                                 vcl.NewStrings,
	"StringsFromInst":                            vcl.StringsFromInst,
	"StringsFromObj":                             vcl.StringsFromObj,
	"StringsFromUnsafePointer":                   vcl.StringsFromUnsafePointer,
	"AsTabSheet":                                 vcl.AsTabSheet,
	"NewTabSheet":                                vcl.NewTabSheet,
	"TabSheetFromInst":                           vcl.TabSheetFromInst,
	"TabSheetFromObj":                            vcl.TabSheetFromObj,
	"TabSheetFromUnsafePointer":                  vcl.TabSheetFromUnsafePointer,
	"AsTaskDialog":                               vcl.AsTaskDialog,
	"NewTaskDialog":                              vcl.NewTaskDialog,
	"TaskDialogFromInst":                         vcl.TaskDialogFromInst,
	"TaskDialogFromObj":                          vcl.TaskDialogFromObj,
	"TaskDialogFromUnsafePointer":                vcl.TaskDialogFromUnsafePointer,
	"AsTaskDialogBaseButtonItem":                 vcl.AsTaskDialogBaseButtonItem,
	"NewTaskDialogBaseButtonItem":                vcl.NewTaskDialogBaseButtonItem,
	"TaskDialogBaseButtonItemFromInst":           vcl.TaskDialogBaseButtonItemFromInst,
	"TaskDialogBaseButtonItemFromObj":            vcl.TaskDialogBaseButtonItemFromObj,
	"TaskDialogBaseButtonItemFromUnsafePointer":  vcl.TaskDialogBaseButtonItemFromUnsafePointer,
	"AsTaskDialogButtonItem":                     vcl.AsTaskDialogButtonItem,
	"NewTaskDialogButtonItem":                    vcl.NewTaskDialogButtonItem,
	"TaskDialogButtonItemFromInst":               vcl.TaskDialogButtonItemFromInst,
	"TaskDialogButtonItemFromObj":                vcl.TaskDialogButtonItemFromObj,
	"TaskDialogButtonItemFromUnsafePointer":      vcl.TaskDialogButtonItemFromUnsafePointer,
	"AsTaskDialogButtons":                        vcl.AsTaskDialogButtons,
	"TaskDialogButtonsFromInst":                  vcl.TaskDialogButtonsFromInst,
	"TaskDialogButtonsFromObj":                   vcl.TaskDialogButtonsFromObj,
	"TaskDialogButtonsFromUnsafePointer":         vcl.TaskDialogButtonsFromUnsafePointer,
	"AsTaskDialogRadioButtonItem":                vcl.AsTaskDialogRadioButtonItem,
	"NewTaskDialogRadioButtonItem":               vcl.NewTaskDialogRadioButtonItem,
	"TaskDialogRadioButtonItemFromInst":          vcl.TaskDialogRadioButtonItemFromInst,
	"TaskDialogRadioButtonItemFromObj":           vcl.TaskDialogRadioButtonItemFromObj,
	"TaskDialogRadioButtonItemFromUnsafePointer": vcl.TaskDialogRadioButtonItemFromUnsafePointer,
	"AsTextAttributes":                           vcl.AsTextAttributes,
	"TextAttributesFromInst":                     vcl.TextAttributesFromInst,
	"TextAttributesFromObj":                      vcl.TextAttributesFromObj,
	"TextAttributesFromUnsafePointer":            vcl.TextAttributesFromUnsafePointer,
	"AsTimer":                                    vcl.AsTimer,
	"NewTimer":                                   vcl.NewTimer,
	"TimerFromInst":                              vcl.TimerFromInst,
	"TimerFromObj":                               vcl.TimerFromObj,
	"TimerFromUnsafePointer":                     vcl.TimerFromUnsafePointer,
	"AsToolBar":                                  vcl.AsToolBar,
	"NewToolBar":                                 vcl.NewToolBar,
	"ToolBarFromInst":                            vcl.ToolBarFromInst,
	"ToolBarFromObj":                             vcl.ToolBarFromObj,
	"ToolBarFromUnsafePointer":                   vcl.ToolBarFromUnsafePointer,
	"AsToolButton":                               vcl.AsToolButton,
	"NewToolButton":                              vcl.NewToolButton,
	"ToolButtonFromInst":                         vcl.ToolButtonFromInst,
	"ToolButtonFromObj":                          vcl.ToolButtonFromObj,
	"ToolButtonFromUnsafePointer":                vcl.ToolButtonFromUnsafePointer,
	"AsTrackBar":                                 vcl.AsTrackBar,
	"NewTrackBar":                                vcl.NewTrackBar,
	"TrackBarFromInst":                           vcl.TrackBarFromInst,
	"TrackBarFromObj":                            vcl.TrackBarFromObj,
	"TrackBarFromUnsafePointer":                  vcl.TrackBarFromUnsafePointer,
	"AsTrayIcon":                                 vcl.AsTrayIcon,
	"NewTrayIcon":                                vcl.NewTrayIcon,
	"TrayIconFromInst":                           vcl.TrayIconFromInst,
	"TrayIconFromObj":                            vcl.TrayIconFromObj,
	"TrayIconFromUnsafePointer":                  vcl.TrayIconFromUnsafePointer,
	"AsTreeNode":                                 vcl.AsTreeNode,
	"NewTreeNode":                                vcl.NewTreeNode,
	"TreeNodeFromInst":                           vcl.TreeNodeFromInst,
	"TreeNodeFromObj":                            vcl.TreeNodeFromObj,
	"TreeNodeFromUnsafePointer":                  vcl.TreeNodeFromUnsafePointer,
	"AsTreeNodes":                                vcl.AsTreeNodes,
	"NewTreeNodes":                               vcl.NewTreeNodes,
	"TreeNodesFromInst":                          vcl.TreeNodesFromInst,
	"TreeNodesFromObj":                           vcl.TreeNodesFromObj,
	"TreeNodesFromUnsafePointer":                 vcl.TreeNodesFromUnsafePointer,
	"AsTreeView":                                 vcl.AsTreeView,
	"NewTreeView":                                vcl.NewTreeView,
	"TreeViewFromInst":                           vcl.TreeViewFromInst,
	"TreeViewFromObj":                            vcl.TreeViewFromObj,
	"TreeViewFromUnsafePointer":                  vcl.TreeViewFromUnsafePointer,
	"AsUpDown":                                   vcl.AsUpDown,
	"NewUpDown":                                  vcl.NewUpDown,
	"UpDownFromInst":                             vcl.UpDownFromInst,
	"UpDownFromObj":                              vcl.UpDownFromObj,
	"UpDownFromUnsafePointer":                    vcl.UpDownFromUnsafePointer,
	"AsValueListEditor":                          vcl.AsValueListEditor,
	"NewValueListEditor":                         vcl.NewValueListEditor,
	"ValueListEditorFromInst":                    vcl.ValueListEditorFromInst,
	"ValueListEditorFromObj":                     vcl.ValueListEditorFromObj,
	"ValueListEditorFromUnsafePointer":           vcl.ValueListEditorFromUnsafePointer,
	"AsWinControl":                               vcl.AsWinControl,
	"NewWinControl":                              vcl.NewWinControl,
	"WinControlFromInst":                         vcl.WinControlFromInst,
	"WinControlFromObj":                          vcl.WinControlFromObj,
	"WinControlFromUnsafePointer":                vcl.WinControlFromUnsafePointer,
	"AsXButton":                                  vcl.AsXButton,
	"NewXButton":                                 vcl.NewXButton,
	"XButtonFromInst":                            vcl.XButtonFromInst,
	"XButtonFromObj":                             vcl.XButtonFromObj,
	"XButtonFromUnsafePointer":                   vcl.XButtonFromUnsafePointer,
}
