package net

import (
	"net"

	qlang "github.com/topxeq/qlang/spec"
)

// Exports is the export table of this module.
//
var Exports = map[string]interface{}{
	"_name": "net",

	"FlagBroadcast":    net.FlagBroadcast,
	"FlagLoopback":     net.FlagLoopback,
	"FlagMulticast":    net.FlagMulticast,
	"FlagPointToPoint": net.FlagPointToPoint,
	"FlagUp":           net.FlagUp,
	"IPv4len":          net.IPv4len,
	"IPv6len":          net.IPv6len,

	"DefaultResolver":            net.DefaultResolver,
	"ErrWriteToConnected":        net.ErrWriteToConnected,
	"IPv4allrouter":              net.IPv4allrouter,
	"IPv4allsys":                 net.IPv4allsys,
	"IPv4bcast":                  net.IPv4bcast,
	"IPv4zero":                   net.IPv4zero,
	"IPv6interfacelocalallnodes": net.IPv6interfacelocalallnodes,
	"IPv6linklocalallnodes":      net.IPv6linklocalallnodes,
	"IPv6linklocalallrouters":    net.IPv6linklocalallrouters,
	"IPv6loopback":               net.IPv6loopback,
	"IPv6unspecified":            net.IPv6unspecified,
	"IPv6zero":                   net.IPv6zero,

	"Dial":               net.Dial,
	"DialIP":             net.DialIP,
	"DialTCP":            net.DialTCP,
	"DialTimeout":        net.DialTimeout,
	"DialUDP":            net.DialUDP,
	"DialUnix":           net.DialUnix,
	"FileConn":           net.FileConn,
	"FileListener":       net.FileListener,
	"FilePacketConn":     net.FilePacketConn,
	"InterfaceAddrs":     net.InterfaceAddrs,
	"InterfaceByIndex":   net.InterfaceByIndex,
	"InterfaceByName":    net.InterfaceByName,
	"Interfaces":         net.Interfaces,
	"JoinHostPort":       net.JoinHostPort,
	"Listen":             net.Listen,
	"ListenIP":           net.ListenIP,
	"ListenMulticastUDP": net.ListenMulticastUDP,
	"ListenPacket":       net.ListenPacket,
	"ListenTCP":          net.ListenTCP,
	"ListenUDP":          net.ListenUDP,
	"ListenUnix":         net.ListenUnix,
	"ListenUnixgram":     net.ListenUnixgram,
	"LookupAddr":         net.LookupAddr,
	"LookupCNAME":        net.LookupCNAME,
	"LookupHost":         net.LookupHost,
	"LookupIP":           net.LookupIP,
	"LookupMX":           net.LookupMX,
	"LookupNS":           net.LookupNS,
	"LookupPort":         net.LookupPort,
	"LookupSRV":          net.LookupSRV,
	"LookupTXT":          net.LookupTXT,
	"ParseCIDR":          net.ParseCIDR,
	"ParseMAC":           net.ParseMAC,
	"Pipe":               net.Pipe,
	"ResolveIPAddr":      net.ResolveIPAddr,
	"ResolveTCPAddr":     net.ResolveTCPAddr,
	"ResolveUDPAddr":     net.ResolveUDPAddr,
	"ResolveUnixAddr":    net.ResolveUnixAddr,
	"SplitHostPort":      net.SplitHostPort,

	"Dialer":       qlang.StructOf((*net.Dialer)(nil)),
	"IPAddr":       qlang.StructOf((*net.IPAddr)(nil)),
	"IPConn":       qlang.StructOf((*net.IPConn)(nil)),
	"IPNet":        qlang.StructOf((*net.IPNet)(nil)),
	"Interface":    qlang.StructOf((*net.Interface)(nil)),
	"ListenConfig": qlang.StructOf((*net.ListenConfig)(nil)),
	"MX":           qlang.StructOf((*net.MX)(nil)),
	"NS":           qlang.StructOf((*net.NS)(nil)),
	"SRV":          qlang.StructOf((*net.SRV)(nil)),
	"TCPAddr":      qlang.StructOf((*net.TCPAddr)(nil)),
	"TCPConn":      qlang.StructOf((*net.TCPConn)(nil)),
	"UDPAddr":      qlang.StructOf((*net.UDPAddr)(nil)),
	"UDPConn":      qlang.StructOf((*net.UDPConn)(nil)),
	"UnixAddr":     qlang.StructOf((*net.UnixAddr)(nil)),
	"UnixConn":     qlang.StructOf((*net.UnixConn)(nil)),
}
