package pterm

import (
	"github.com/pterm/pterm"

	qlang "github.com/topxeq/qlang/spec"
)

// Exports is the export table of this module.
//
var Exports = map[string]interface{}{
	"_name": "github.com/pterm/pterm",

	"BgBlack":        pterm.BgBlack,
	"BgBlue":         pterm.BgBlue,
	"BgCyan":         pterm.BgCyan,
	"BgDarkGray":     pterm.BgDarkGray,
	"BgDefault":      pterm.BgDefault,
	"BgGray":         pterm.BgGray,
	"BgGreen":        pterm.BgGreen,
	"BgLightBlue":    pterm.BgLightBlue,
	"BgLightCyan":    pterm.BgLightCyan,
	"BgLightGreen":   pterm.BgLightGreen,
	"BgLightMagenta": pterm.BgLightMagenta,
	"BgLightRed":     pterm.BgLightRed,
	"BgLightWhite":   pterm.BgLightWhite,
	"BgLightYellow":  pterm.BgLightYellow,
	"BgMagenta":      pterm.BgMagenta,
	"BgRed":          pterm.BgRed,
	"BgWhite":        pterm.BgWhite,
	"BgYellow":       pterm.BgYellow,
	"Blink":          pterm.Blink,
	"Bold":           pterm.Bold,
	"Concealed":      pterm.Concealed,
	"FastBlink":      pterm.FastBlink,
	"FgBlack":        pterm.FgBlack,
	"FgBlue":         pterm.FgBlue,
	"FgCyan":         pterm.FgCyan,
	"FgDarkGray":     pterm.FgDarkGray,
	"FgDefault":      pterm.FgDefault,
	"FgGray":         pterm.FgGray,
	"FgGreen":        pterm.FgGreen,
	"FgLightBlue":    pterm.FgLightBlue,
	"FgLightCyan":    pterm.FgLightCyan,
	"FgLightGreen":   pterm.FgLightGreen,
	"FgLightMagenta": pterm.FgLightMagenta,
	"FgLightRed":     pterm.FgLightRed,
	"FgLightWhite":   pterm.FgLightWhite,
	"FgLightYellow":  pterm.FgLightYellow,
	"FgMagenta":      pterm.FgMagenta,
	"FgRed":          pterm.FgRed,
	"FgWhite":        pterm.FgWhite,
	"FgYellow":       pterm.FgYellow,
	"Fuzzy":          pterm.Fuzzy,
	"Italic":         pterm.Italic,
	"Reset":          pterm.Reset,
	"Reverse":        pterm.Reverse,
	"Strikethrough":  pterm.Strikethrough,
	"Underscore":     pterm.Underscore,

	"ActiveProgressBarPrinters":    pterm.ActiveProgressBarPrinters,
	"Black":                        pterm.Black,
	"Blue":                         pterm.Blue,
	"Cyan":                         pterm.Cyan,
	"Debug":                        pterm.Debug,
	"DefaultBasicText":             pterm.DefaultBasicText,
	"DefaultBigText":               pterm.DefaultBigText,
	"DefaultBulletList":            pterm.DefaultBulletList,
	"DefaultCenter":                pterm.DefaultCenter,
	"DefaultHeader":                pterm.DefaultHeader,
	"DefaultPanel":                 pterm.DefaultPanel,
	"DefaultParagraph":             pterm.DefaultParagraph,
	"DefaultProgressbar":           pterm.DefaultProgressbar,
	"DefaultSection":               pterm.DefaultSection,
	"DefaultSpinner":               pterm.DefaultSpinner,
	"DefaultTable":                 pterm.DefaultTable,
	"DefaultTree":                  pterm.DefaultTree,
	"Description":                  pterm.Description,
	"ErrHexCodeIsInvalid":          pterm.ErrHexCodeIsInvalid,
	"ErrTerminalSizeNotDetectable": pterm.ErrTerminalSizeNotDetectable,
	"Error":                        pterm.Error,
	"FallbackTerminalHeight":       pterm.FallbackTerminalHeight,
	"FallbackTerminalWidth":        pterm.FallbackTerminalWidth,
	"Fatal":                        pterm.Fatal,
	"Gray":                         pterm.Gray,
	"GrayBoxStyle":                 pterm.GrayBoxStyle,
	"Green":                        pterm.Green,
	"Info":                         pterm.Info,
	"LightBlue":                    pterm.LightBlue,
	"LightCyan":                    pterm.LightCyan,
	"LightGreen":                   pterm.LightGreen,
	"LightMagenta":                 pterm.LightMagenta,
	"LightRed":                     pterm.LightRed,
	"LightWhite":                   pterm.LightWhite,
	"LightYellow":                  pterm.LightYellow,
	"Magenta":                      pterm.Magenta,
	"Normal":                       pterm.Normal,
	"Output":                       pterm.Output,
	"PrintColor":                   pterm.PrintColor,
	"PrintDebugMessages":           pterm.PrintDebugMessages,
	"Red":                          pterm.Red,
	"Success":                      pterm.Success,
	"ThemeDefault":                 pterm.ThemeDefault,
	"Warning":                      pterm.Warning,
	"White":                        pterm.White,
	"Yellow":                       pterm.Yellow,

	"DisableColor":          pterm.DisableColor,
	"DisableDebugMessages":  pterm.DisableDebugMessages,
	"DisableOutput":         pterm.DisableOutput,
	"EnableColor":           pterm.EnableColor,
	"EnableDebugMessages":   pterm.EnableDebugMessages,
	"EnableOutput":          pterm.EnableOutput,
	"Fprint":                pterm.Fprint,
	"Fprintln":              pterm.Fprintln,
	"Fprinto":               pterm.Fprinto,
	"GetTerminalHeight":     pterm.GetTerminalHeight,
	"GetTerminalSize":       pterm.GetTerminalSize,
	"GetTerminalWidth":      pterm.GetTerminalWidth,
	"Print":                 pterm.Print,
	"Printf":                pterm.Printf,
	"Println":               pterm.Println,
	"Printo":                pterm.Printo,
	"RemoveColorFromString": pterm.RemoveColorFromString,
	"SetDefaultOutput":      pterm.SetDefaultOutput,
	"Sprint":                pterm.Sprint,
	"Sprintf":               pterm.Sprintf,
	"Sprintln":              pterm.Sprintln,
	"Sprinto":               pterm.Sprinto,

	"BasicTextPrinter":            qlang.StructOf((*pterm.BasicTextPrinter)(nil)),
	"BigTextPrinter":              qlang.StructOf((*pterm.BigTextPrinter)(nil)),
	"BulletListItem":              qlang.StructOf((*pterm.BulletListItem)(nil)),
	"bulletlistitem":              pterm.NewBulletListItemFromString,
	"NewBulletListItemFromString": pterm.NewBulletListItemFromString,
	"BulletListPrinter":           qlang.StructOf((*pterm.BulletListPrinter)(nil)),
	"NewBulletListFromString":     pterm.NewBulletListFromString,
	"NewBulletListFromStrings":    pterm.NewBulletListFromStrings,
	"CenterPrinter":               qlang.StructOf((*pterm.CenterPrinter)(nil)),
	"HeaderPrinter":               qlang.StructOf((*pterm.HeaderPrinter)(nil)),
	"Letter":                      qlang.StructOf((*pterm.Letter)(nil)),
	"LeveledListItem":             qlang.StructOf((*pterm.LeveledListItem)(nil)),
	"Panel":                       qlang.StructOf((*pterm.Panel)(nil)),
	"PanelPrinter":                qlang.StructOf((*pterm.PanelPrinter)(nil)),
	"ParagraphPrinter":            qlang.StructOf((*pterm.ParagraphPrinter)(nil)),
	"Prefix":                      qlang.StructOf((*pterm.Prefix)(nil)),
	"PrefixPrinter":               qlang.StructOf((*pterm.PrefixPrinter)(nil)),
	"RGB":                         qlang.StructOf((*pterm.RGB)(nil)),
	"NewRGB":                      pterm.NewRGB,
	"NewRGBFromHEX":               pterm.NewRGBFromHEX,
	"Scope":                       qlang.StructOf((*pterm.Scope)(nil)),
	"SectionPrinter":              qlang.StructOf((*pterm.SectionPrinter)(nil)),
	"SpinnerPrinter":              qlang.StructOf((*pterm.SpinnerPrinter)(nil)),
	"TablePrinter":                qlang.StructOf((*pterm.TablePrinter)(nil)),
	"Theme":                       qlang.StructOf((*pterm.Theme)(nil)),
	"TreeNode":                    qlang.StructOf((*pterm.TreeNode)(nil)),
	"NewTreeFromLeveledList":      pterm.NewTreeFromLeveledList,
	"TreePrinter":                 qlang.StructOf((*pterm.TreePrinter)(nil)),

	// by madarin

	`NewLettersFromString`:          pterm.NewLettersFromString,
	`NewLettersFromStringWithStyle`: pterm.NewLettersFromStringWithStyle,
	`NewStyle`:                      pterm.NewStyle,
}
