package widget

import (
	"fyne.io/fyne/v2/widget"

	qlang "github.com/topxeq/qlang/spec"
)

// Exports is the export table of this module.
//
var Exports = map[string]interface{}{
	"_name": "fyne.io/fyne/v2/widget",

	"ButtonAlignCenter":      widget.ButtonAlignCenter,
	"ButtonAlignLeading":     widget.ButtonAlignLeading,
	"ButtonAlignTrailing":    widget.ButtonAlignTrailing,
	"ButtonIconLeadingText":  widget.ButtonIconLeadingText,
	"ButtonIconTrailingText": widget.ButtonIconTrailingText,
	"HighImportance":         widget.HighImportance,
	"Horizontal":             widget.Horizontal,
	"LowImportance":          widget.LowImportance,
	"MediumImportance":       widget.MediumImportance,
	"Vertical":               widget.Vertical,

	"TextGridStyleDefault":    widget.TextGridStyleDefault,
	"TextGridStyleWhitespace": widget.TextGridStyleWhitespace,

	"ShowModalPopUp":          widget.ShowModalPopUp,
	"ShowPopUp":               widget.ShowPopUp,
	"ShowPopUpAtPosition":     widget.ShowPopUpAtPosition,
	"ShowPopUpMenuAtPosition": widget.ShowPopUpMenuAtPosition,

	"NewToolbarAction":    widget.NewToolbarAction,
	"NewToolbarSeparator": widget.NewToolbarSeparator,
	"NewToolbarSpacer":    widget.NewToolbarSpacer,

	"Accordion":              qlang.StructOf((*widget.Accordion)(nil)),
	"accordion":              widget.NewAccordion,
	"NewAccordion":           widget.NewAccordion,
	"AccordionItem":          qlang.StructOf((*widget.AccordionItem)(nil)),
	"accordionitem":          widget.NewAccordionItem,
	"NewAccordionItem":       widget.NewAccordionItem,
	"NewButton":              widget.NewButton,
	"NewButtonWithIcon":      widget.NewButtonWithIcon,
	"Card":                   qlang.StructOf((*widget.Card)(nil)),
	"card":                   widget.NewCard,
	"NewCard":                widget.NewCard,
	"NewCheck":               widget.NewCheck,
	"NewCheckWithData":       widget.NewCheckWithData,
	"CustomTextGridStyle":    qlang.StructOf((*widget.CustomTextGridStyle)(nil)),
	"NewEntry":               widget.NewEntry,
	"NewEntryWithData":       widget.NewEntryWithData,
	"NewMultiLineEntry":      widget.NewMultiLineEntry,
	"NewPasswordEntry":       widget.NewPasswordEntry,
	"fileicon":               widget.NewFileIcon,
	"NewFileIcon":            widget.NewFileIcon,
	"form":                   widget.NewForm,
	"NewForm":                widget.NewForm,
	"formitem":               widget.NewFormItem,
	"NewFormItem":            widget.NewFormItem,
	"NewHyperlink":           widget.NewHyperlink,
	"NewHyperlinkWithStyle":  widget.NewHyperlinkWithStyle,
	"icon":                   widget.NewIcon,
	"NewIcon":                widget.NewIcon,
	"NewLabel":               widget.NewLabel,
	"NewLabelWithData":       widget.NewLabelWithData,
	"NewLabelWithStyle":      widget.NewLabelWithStyle,
	"NewList":                widget.NewList,
	"NewListWithData":        widget.NewListWithData,
	"menu":                   widget.NewMenu,
	"NewMenu":                widget.NewMenu,
	"popup":                  widget.NewPopUp,
	"NewPopUp":               widget.NewPopUp,
	"NewModalPopUp":          widget.NewModalPopUp,
	"popupmenu":              widget.NewPopUpMenu,
	"NewPopUpMenu":           widget.NewPopUpMenu,
	"NewProgressBar":         widget.NewProgressBar,
	"NewProgressBarWithData": widget.NewProgressBarWithData,
	"ProgressBarInfinite":    qlang.StructOf((*widget.ProgressBarInfinite)(nil)),
	"progressbarinfinite":    widget.NewProgressBarInfinite,
	"NewProgressBarInfinite": widget.NewProgressBarInfinite,
	"radiogroup":             widget.NewRadioGroup,
	"NewRadioGroup":          widget.NewRadioGroup,
	"select":                 widget.NewSelect,
	"NewSelect":              widget.NewSelect,
	"selectentry":            widget.NewSelectEntry,
	"NewSelectEntry":         widget.NewSelectEntry,
	"Separator":              qlang.StructOf((*widget.Separator)(nil)),
	"separator":              widget.NewSeparator,
	"NewSeparator":           widget.NewSeparator,
	"NewSlider":              widget.NewSlider,
	"NewSliderWithData":      widget.NewSliderWithData,
	"table":                  widget.NewTable,
	"NewTable":               widget.NewTable,
	"TableCellID":            qlang.StructOf((*widget.TableCellID)(nil)),
	"TextGrid":               qlang.StructOf((*widget.TextGrid)(nil)),
	"NewTextGrid":            widget.NewTextGrid,
	"NewTextGridFromString":  widget.NewTextGridFromString,
	"TextGridCell":           qlang.StructOf((*widget.TextGridCell)(nil)),
	"TextGridRow":            qlang.StructOf((*widget.TextGridRow)(nil)),
	"Toolbar":                qlang.StructOf((*widget.Toolbar)(nil)),
	"toolbar":                widget.NewToolbar,
	"NewToolbar":             widget.NewToolbar,
	"ToolbarAction":          qlang.StructOf((*widget.ToolbarAction)(nil)),
	"ToolbarSeparator":       qlang.StructOf((*widget.ToolbarSeparator)(nil)),
	"ToolbarSpacer":          qlang.StructOf((*widget.ToolbarSpacer)(nil)),
	"NewTree":                widget.NewTree,
	"NewTreeWithStrings":     widget.NewTreeWithStrings,
}
